---
title: "README_ECiA_Professional_Skills_B250279"
author: "Alexander Eyo"
date: "2023-11-25"
output: html_document

This project was carried out with regard to a proposal by a landowner to plant commercial forestry on one of two potential plots of land on the isle of Arran (off the west coast of Scotland). The aims of this project were to perform a desk study, phase 1 habitat survey and ecological survey of these plot areas analyse the data and interperet the results to inform the landowner of the species of plants, vertebrates and invertebrates present within the plots and assess the ecological impacts that a commercial forest plantation might have on the local fauna and flora in order to inform a decision as to which plot would be most suitable for the plantation, if any. The data was collected for the ecological survey using standard sampling methods (Transects, point counts, camera traps etc). It was found that both plots contained protected habitats and species that were of conservation priority. The northern plot was located in a national scenic area (NSA) and in addition the southern plot was also located in a site of special scientific interest (SSI). Given this information it was concluded that neither plot was suitable for a commercial forestry plantation.

for questions and further info email: eyo.alexander@gmail.com
